# Generated by Django 3.0.7 on 2020-06-11 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='listing',
        ),
    ]
